version: "2.4"

networks:
  arquitectura:
    name: network-backend
    ipam:
      driver: default
      config:
        - subnet: "192.30.0.0/16"
          gateway: "192.30.0.1"
  software:
    name: network-config-server
    external: true

services:
  ms-discovery:
    image: ms-discovery:1.0.0
    mem_limit: 300m
    ports:
      - "8761:8761"
    # environment:
    #- "EUREKA_URI=http://192.168.0.159:8761/eureka"
    networks:
      - software
      - arquitectura
  ms-gateway:
    image: ms-gateway:1.0.0
    mem_limit: 300m
    ports:
      - "8282:8282"
    environment:
      - "EUREKA_URI=http://ms-discovery:8761/eureka"
    depends_on:
      ms-discovery:
        condition: service_started
    networks:
      - software
      - arquitectura
  ms-product:
    image: ms-product:1.0.0
    mem_limit: 300m
    ports:
      - "5000:5000"
    environment:
      - "EUREKA_URI=http://ms-discovery:8761/eureka"
      - "CONFIG_URI=http://config-server:8888"
    depends_on:
      ms-discovery:
        condition: service_started
    networks:
      - software
      - arquitectura
  ms-checkout:
    image: ms-checkout:1.0.0
    mem_limit: 300m
    ports:
      - "5001:5001"
    environment:
      - "EUREKA_URI=http://ms-discovery:8761/eureka"
      - "CONFIG_URI=http://config-server:8888"
    depends_on:
      ms-discovery:
        condition: service_started
    networks:
      - software
      - arquitectura
  ms-dashboard:
    image: ms-dashboard:1.0.0
    mem_limit: 300m
    ports:
      - "5002:5002"
    environment:
      - "EUREKA_URI=http://ms-discovery:8761/eureka"
      - "CONFIG_URI=http://config-server:8888"
    depends_on:
      ms-discovery:
        condition: service_started
    networks:
      - software
      - arquitectura

#DESDE AQUI HAY QUE CORREGIR
#  ms-zipkin:
#    image: ms-zipkin:1.0.0
#    mem_limit: 300m
#    ports:
#      - "9091:9091"
#    environment:
#      - "EUREKA_URI=http://192.168.0.159:8761/eureka"
    #depends_on:
    #  ms-discovery:
    #    condition: service_started
#    networks:
#      - software
#      - arquitectura
#  walikidb:
#    image: cdmmucb/walikidb:1.0.0
#    mem_limit: 300m
#    ports:
#      - "3600:3600"
    # environment:
    #- "EUREKA_URI=http://192.168.0.159:8761/eureka"
#    networks:
#      - software
#      - arquitectura