server:
  port: ${SERVER_PORT:5000}

spring:
  application:
    name: ms-product

eureka:
  instance:
    preferIpAddress: false
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
